name: CI - lint and unit tests

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    # secrets not needed for now, perhaps for e2e testing
    # env:
    #   GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
    #   GOODREADS_USER: ${{ secrets.GOODREADS_USER }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Unit tests (deno)
        run: |
          deno --version
          deno lint src
          deno test src

      - name: Setup CUE
        # uses: cue-lang/setup-cue@v1.0.0-alpha.2
        # test my fork: https://github.com/daneroo/setup-cue
        # Using my own fork: PR: https://github.com/cue-lang/setup-cue/pull/10
        uses: daneroo/setup-cue@main
        with:
          version: "v0.4.3" # default is latest
        id: install

      - name: Check CUE version
        run: cue version

      - name: Integration -  CUE Validate Intermediate RSS files checker
        run: cue vet check-rss.cue goodreads-rss-p1-example.json
        working-directory: cue

      - name: Integration -  CUE Validate Final Output with CUE
        run: cue vet check-output.cue goodreads-rss-example.json
        working-directory: cue
