name: CI - lint and unit tests

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    # secrets not needed for now, perhaps for e2e testing
    # env:
    #   GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
    #   GOODREADS_USER: ${{ secrets.GOODREADS_USER }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: oven-sh/setup-bun@v2
        with:
          # 1.x is working but docs say to use 1.0.x : I want minor updates too!
          bun-version: 1.x
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - uses: cue-lang/setup-cue@v1.0.1
        with:
          version: "v0.7.1" # default is latest
        id: install

      - name: Report versions
        run: |
          echo "pnpm: $(pnpm --version)"
          echo "node: $(node --version)"
          echo "bun: $(bun --version)"
          deno --version
          cue version

      # pnpm i --frozen-lockfile
      - name: Run Unit tests & lint (all)
        run: |
          pnpm lint
          pnpm test
