name: CI - lint and unit tests

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    # secrets not needed for now, perhaps for e2e testing
    # env:
    #   GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
    #   GOODREADS_USER: ${{ secrets.GOODREADS_USER }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Unit tests (deno)
        run: |
          deno --version
          deno lint src
          deno test src

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          # commented for local run
          # cache: 'npm'

      - name: Run Unit tests (node)
        run: |
          npm ci
          npm test


