name: CI - lint and unit tests

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    # secrets not needed for now, perhaps for e2e testing
    # env:
    #   GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
    #   GOODREADS_USER: ${{ secrets.GOODREADS_USER }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: daneroo/setup-cue@main
        # uses: cue-lang/setup-cue@v1.0.0-alpha.2
        # test my fork: https://github.com/daneroo/setup-cue
        # Using my own fork: PR: https://github.com/cue-lang/setup-cue/pull/10
        with:
          version: "v0.5.0" # default is latest
        id: install

      - name: Report versions
        run: |
          deno --version
          node --version
          pnpm --version
          cue version

      # pnpm i --frozen-lockfile
      - name: Run Unit tests & lint (all)
        run: |
          pnpm lint
          pnpm test
